### PR TITLE
Circularized MIKE to 80x80 and added DELTA to MIKE

### PR DESCRIPTION
**Pull request by Pds314**

### CODE REVIEW

**Comment by Pds314** [comment]
KILO LIGHT added

**Comment by Pds314** [comment]
KILO ULTRALIGHT added.

**Comment by Pds314** [comment]
Added KILO ULTRALIGHT PLUS. 2968 kg to Jool intercept with a 1306 m/s drop tank.

**Comment by Pds314** [comment]
Ladder truck

**Comment by maneatingape** [comment]
Cherry-picked commit with update save file.
KILO update can be submitted in new PR.

**Pull request closed without merging**
